# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-28 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20170426_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='', upload_to='teachers/%Y/%m', verbose_name='\u673a\u6784LOGO\u56fe'),
        ),
    ]
